// Code generated by goctl. DO NOT EDIT.
package types

type LoginResponse struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Token    string `json:"token"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type UserRegisterResponse struct {
	Message string `json:"message"`
	Code    int    `json:"code"`
}

type UserRegisterRequest struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}
